---

- name: Install firewalld
  package: name={{ item }} state=present
  with_items:
    - firewalld

- name: Remove unwanted packages
  package: state=absent name={{ item }}
  with_items:
   - iptables-services
  tags:
  - packages
  - base

- name: Install Fedora core packages
  when: ansible_distribution == "Fedora"
  package: name={{ item }} state=present
  with_items:
    - python3-firewall
    - python3-policycoreutils
    - dnf-automatic

- name: Install dnf-automatic configuration
  template: src=dnf-automatic.j2 dest=/etc/dnf/automatic.conf owner=root group=root mode=0644
  when: ansible_distribution == "Fedora"

- name: Enable dnf-automatic-download
  service: name=dnf-automatic-download.timer state=started enabled=yes
  when: ansible_distribution == "Fedora"

- name: Enable dnf-automatic-install
  service: name=dnf-automatic-install.timer state=started enabled=yes
  when: ansible_distribution == "Fedora"

- name: Ensure firewalld is running
  service: name=firewalld state=started enabled=true
