---

- name: Install httpd
  package: name={{ item }} state=present
  with_items:
    - httpd
    - mod_ssl
    - python3-mod_wsgi

- name: open firewall ports
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - http
    - https
  notify: reload firewalld

- name: start httpd
  service: name=httpd state=started enabled=yes
