# Generated by Django 2.2.6 on 2019-11-08 07:20
"""Add a field to a Git Forge for configuring the development branch."""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patchlab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitforge",
            name="development_branch",
            field=models.CharField(default="master", max_length=255),
        ),
        migrations.AlterField(
            model_name="gitforge",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="git_forge",
                serialize=False,
                to="patchwork.Project",
            ),
        ),
    ]
