---
- name: Install database packages
  package: name={{ item }} state=present
  with_items:
      - postgresql-server
      - postgresql-devel
      - postgresql
      - python3-psycopg2

- name: check for postgres db
  find:
    paths: /var/lib/pgsql/data
    depth: 1
    file_type: any
  register: pg_init

- name: init postgres db
  command: postgresql-setup initdb
  when: pg_init.matched == 0

- replace:
    dest: /var/lib/pgsql/data/pg_hba.conf
    regexp: "host    all             all             127.0.0.1/32            ident"
    replace: "host    all             all             127.0.0.1/32            trust"
  notify: restart postgres

- replace:
    dest: /var/lib/pgsql/data/pg_hba.conf
    regexp: "local   all             all                                     peer"
    replace: "local   all             all                                     trust"
  notify: restart postgres

- replace:
    dest: /var/lib/pgsql/data/pg_hba.conf
    regexp: "host    all             all             ::1/128                 ident"
    replace: "host    all             all             ::1/128                 trust"
  notify: restart postgres

- service:
    name: postgresql
    state: started
    enabled: yes

- name: Create databases
  postgresql_db:
    name: "patchwork"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: true
  become_user: postgres

- name: Create databases
  postgresql_db:
    name: "patchwork_test"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: true
  become_user: postgres

- name: Create database users
  postgresql_user:
    state: present
    db: "patchwork"
    name: "patchwork"
    password: "password"
    role_attr_flags: SUPERUSER,CREATEROLE,CREATEDB
  become: true
  become_user: postgres
