name: Pull request checks

on:
  pull_request:
    branches:
      - master

jobs:
  py37:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Lint with flake8
      run: |
        tox -e lint
    - name: Format check with Black
      run: |
        tox -e format
    - name: License check with liccheck
      run: |
        tox -e licenses
    - name: Security check with Bandit
      run: |
        tox -e bandit
    - name: Test with pytest
      run: |
        tox -e py37
    - name: Test documentation with sphinx
      run: |
        tox -e docs
