name: Pull request checks

on:
  pull_request:
    branches:
      - master

jobs:
  style_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox_job: ["lint", "format", "licenses", "bandit", "docs"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Checking ${{ matrix.tox_job }}
      run: tox -e ${{ matrix.tox_job }}
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash
        sudo apt-get update -y
        sudo apt-get install -y --fix-missing ansible rabbitmq-server python-psycopg2
        sudo systemctl start rabbitmq-server
        sudo ansible-galaxy install geerlingguy.postgresql
        sudo ansible-playbook devel/ansible/ci-playbook.yml
        python -m pip install --upgrade pip
        pip install tox codecov
    - name: Test with pytest
      run: tox -e py${{ matrix.python-version }}
    - name: Upload coverage results
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: codecov
